server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_format: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange-db
    username: test-user
    password: 1



jwt:
  token:
    secret: tanos
    validity: 86400000